CIPHERTEXT = "HT YZVMZNO ZGGZI, RZ VMZ, VO GVNO, VMMDQZY DI IZR TJMF, VIY D XVIIJO OZGG TJP CJR CVKKT D VH OJ WZ CZMZ. VAOZM V GJIB VIY VMYPJPN NZV EJPMIZT D XVIIJO NVT DO DN OCZ WZNO JA ODHZN, WPO DO DN AVM AMJH OCZ RJMNO! OCVIF TJP NJ HPXC AJM XJHHZIYDIB HZ OJ TJPM AMDZIY HM YDXFZIN. CZ DN V YZHVIYDIB ZHKGJTZM, WPO IJO PIFDIY, VIY OCZ RJMF DN ZIBVBDIB VIY MZRVMYDIB DI ZLPVG HZVNPMZ. ZIXJPMVBZY WT CDN BJJY AMDZIY HM RDGFDZ, CZ CVN WZBPI OJ XJINDYZM V IZR IJQZG DI OCZ NOTGZ JA V HTNOZMT, VIY D OCDIF DO HDBCO WZ CDN ADIZNO DYZV TZO. D VH IJO XZMOVDI RCZOCZM OCZ QJTVBZ DONZGA CVN ODMZY CDH, WPO CZ CVN NZZHZY DI GJR NKDMDON NDIXZ RZ VMMDQZY, VIY D VH CJKDIB OCVO OCDN IZR KMJEZXO RDGG CZGK OJ GDAO OCZH. D RJIYZM DA CDN YZHZVIJPM DN DI KVMO MZGVOZY OJ OCZ VKKZVMVIXZ JA V MVOCZM NOMVIBZ IJOZ OCVO RVN YZGDQZMZY OJ CDN XVWDI JI VMMDQVG DI OCZ KJMO. DO DN HJNO DIOMDBPDIB. VN TJP FIJR, D VH MZLPDMZY OJ JKZI VIY NJMO VGG OCZ HVDG, YZOZMHDIDIB RCDXC GZOOZMN, DA VIT, MZLPDMZ HM YDXFZIN VOOZIODJI. OCZ GZOOZM RVN HVMFZY \”NOMDXOGT KMDQVOZ AJM HM XCVMGZN YDXFZIN”, WPO D XJIAZNN D CVY VGMZVYT JKZIZY OCZ ZIQZGJKZ WZAJMZ D IJODXZY OCZ NOZMI DIEPIXODJI VIY OCZMZAJMZ CVY NZZI OCZ XJIOZION RCDXC RZMZ IJO AJM HT ZTZN. D NVT NZZI MVOCZM OCVI MZVY, AJM DO RVN DHKJNNDWGZ OJ MZVY OCZ RJMYN OCZMZDI, DA DIYZZY OCZT RZMZ RJMYN! OCZ XCVMVXOZMN, RCDGZ AVHDGDVM, HVYZ IJ NZINZ VIY D YZOZMHDIZY OJ MZKGVXZ OCZ GZOOZM DI DON ZIQZGJKZ VIY OJ KVNN DO OJ HM YDXFZIN RDOC HT VKJGJBDZN. CZ OJJF DO, NVTDIB IJOCDIB VIY NKZIO NJHZ ODHZ VGJIZ DI CDN XVWDI. D YDY IJO NZZ OCZ GZOOZM VBVDI WPO YDY YDNXJQZM V NHVGG KDGZ JA VNC DI V YDNC PKJI CDN YZNF. PIVWGZ OJ NPKKMZNN HT XPMDJNDOT D ZILPDMZY JA OCZ NCDK\’N NOZRVMY DA CZ FIZR VITOCDIB JA OCDN IJOZ, VIY CZ OJGY HZ OCVO DO CVY WZZI YZGDQZMZY WT CVIY, WT V HVI FIJRI OJ OCZ XMZR VN NZXMZOVMT OJ HM BMZIQDGGZ H. YJYBZ. D FIJR IJOCDIB JA OCDN HVI, WZTJIY OCZ AVXO OCVO CZ DN V RZVGOCT DIYPNOMDVGDNO, VIY D XVI JIGT NPKKJNZ OCVO CZ DN CJKDIB OJ HZZO OCZ AVHJPN VPOCJM KMDQVOZGT. DA NJ, D OCDIF CZ HVT WZ YDNVKKJDIOZY. JPM NXCZYPGZ DN VGMZVYT APGG, VIY D XVIIJO OCDIF OCVO RZ NCJPGY QVMT DO DI MZNKJINZ OJ OCZ HVIT NPXC MZLPZNON. NODGG, D XVIIJO ZNXVKZ OCZ DHKMZNNDJI OCVO OCDN RVN HJMZ OCVI V KMDQVOZ DIQDOVODJI. DA DO RZMZ OCZI D XVIIJO NZZ RCT DON XJIOZION RJPGY IZZY OJ WZ NZXPMZY. DO NZZHN OCZMZ HVT WZ HJMZ OCVI JIZ HTNOZMT VO CVIY. TJPMN NDIXZMZGT, XGVMV"
CIPHERTEXT_PART_B = "FRWXT KFKWB VDXGL BMKNL MMATM RHNKC HNKGX RPTLN GXOXG MYNET GWAHI XRHNP BEEGH MFBGW FRWBK XVMGX LLBGP KBMBG ZMHRH NHGRH NKTKK BOTEB GGXPR HKDBT IIKXV BTMXM ATMRH NFTRG XXWTE BMMEX MBFXM HLXMR HNKHP GIETG LBGFH MBHGU NMMAB GZLTK XFHOB GZLHF XPATM YTLMX KMATG BXGOB LTZXW PAXGB YBKLM TIIKH TVAXW FKUTU UTZXP BMAFR IKHIH LTEBY XTKMA TMBGM AXLXW TGZXK HNLMB FXLBM BLGXV XLLTK RMHKX TVMMH XOXGM LPBMA LIXXW BYPXT KXMHA TOXTG RAHIX HYLAT IBGZH NKWXL MBGRP BMAEN VDBMB LGHMM HHETM XMHXF UTKDH GHNKO XGMNK XBNGW XKLMT GWMAT MRHNK LVAXW NEXBL GHMRX MYBGT EBLXW LHVTG BBFIE HKXRH NMHVH GLBWX KFHOB GZYHK PTKWR HNKOB LBMMH PTLAB GZMHG MAXKX TKXIX HIEXA XKXHY VHGLX JNXGV XPAHT KXXTZ XKMHF XXMPB MARHN TGWPA HFBZA MUXIX KLNTW XWURR HNMHC HBGPB MANLB YMAXL TVKBY BVXHY LHFTG RZHHW FXGTG WPHFX GBLGH MMHUX PTLMX WMAXG PXPBE EGXXW MAXBK LNIIH KMRHN ATOXT EKXTW RLAHP GTKXF TKDTU EXLDB EEBGX QIHLB GZBGC NLMBV XTGWI XKLNT WBGZM AXPXT EMARM HPHKD PBMAR HNMHT WWKXL LBMHG RHNKL BWXHY MAXTM ETGMB VAXKX BGMAX NGBMX WLMTM XLPXT KXWXL IXKTM XERBG GXXWH YRHNK TWOHV TVRBY PXTKX MHVHG LHEBW TMXMA XZTBG LPHGB GHNKF HLMNG VBOBE PTKPB MAFRO XKRUX LMPBL AXLZK XGOBE EXFWH WZX"

def decrypt_caesar(ciphertext: str, shift: int) -> str:
    decrypted = []
    for char in ciphertext:
        if char.isalpha():
            base = ord('A') if char.isupper() else ord('a')
            decrypted_char = chr((ord(char) - base - shift) % 26 + base)
            decrypted.append(decrypted_char)
        else:
            decrypted.append(char)
    return ''.join(decrypted)

for i in range(1, 26):
    print("\n\n\n-----------------------------------")
    print(f"Shift {i}: {decrypt_caesar(CIPHERTEXT, i)}")
    print("-----------------------------------\n\n\n")

for i in range(1, 26):
    print("\n\n\n-----------------------------------")
    print(f"Shift {i}: {decrypt_caesar(CIPHERTEXT_PART_B, i)}")
    print("-----------------------------------\n\n\n")